### ISSUE TITLE
Question about CLI instructions in Usage guide (wiki)

### ISSUE THREAD

**Issue by rpgoldman** [effiban/scala2java#1076]
The Usage guide specifies:

> To generate output to the console run the following command:
`java -jar scala2java-core_2.13-<version>-all.jar -cp <project_classpath>  MyClass1.scala MyClass2.scala`

But for me at least this gives the error:

```
 $  java -jar ~/Downloads/scala2java_2.13-1.0.3-all.jar -cp ../src:../../lib Satisfaction.scala

================================================================================
   Translation of Scala file: -cp
================================================================================
```

So it seems that the `-cp` option is not understood by the application.

**Comment by effiban** [comment]
Hi @rpgoldman ,
Sorry for the slow response.
Please make sure you're using the latest version of the tool which is **10.0.1** or some other version not far behind.
Your example shows that you're using **1.0.3**

**Comment by rpgoldman** [comment]
Thank you very much!
