### ISSUE TITLE
Facing issue while running the all jar 

### ISSUE THREAD

**Issue by mahajpuneet** [effiban/scala2java#422]
Keep getting this error while trying to run as per doc:
`java.lang.UnsupportedClassVersionError: io/github/effiban/scala2java/core/Scala2JavaRunner has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 56.0
`

**Comment by mahajpuneet** [comment]
My java version: 
`(base) BLRL-300075517:spark 300075517$ java --version
java 12.0.1 2019-04-16`

**Comment by effiban** [comment]
Hi @mahajpuneet ,
First of all thanks for trying out the tool :)
You must use **Java 17** for this tool

**Comment by mahajpuneet** [comment]
Thanks worked
